### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by schmm2**
fix typo and adjust quotes according to blog post: https://sysmansquad.com/2020/06/08/deploy-languages-via-software-center-with-pscmwin10language/

### CODE REVIEW

**Comment by schmm2** [comment]
Ran into a issue...blindly copy pasting the code and found a $ which I assume is wrong there ;)

**Comment by codaamok** [comment]
Ah, thank you so much! Will publish to the gallery later

**Comment by codaamok** [comment]
No, I won't be publishing to gallery later because all that change was the README. Sometimes I wonder how I function at all. Thanks again for your help.

**Comment by schmm2** [comment]
I have the same feeling alot of times.Thanks for your awesome scripts and blog posts. You really saved my day. I hope I will get the change of buying you a beer one day ;) On 12 Jan 2021 22:23, Adam Cook <notifications@github.com> wrote:
No, I won't be publishing to gallery later because all that change was the README. Sometimes I wonder how I function at all. Thanks again for your help.

**Comment by codaamok** [comment]
I appreciate the kind words ❤️ enjoy the rest of your day!

**Pull request merged**
